apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend 
  ports:
    - name: "http"
      port: 443
      targetPort: 5000 
      nodePort: 31500